### ISSUE TITLE
Deploy archetype's -SNAPSHOT to public Maven repository

### ISSUE THREAD

**Issue by manandbytes** [caniszczyk/minerva#16]
Hi Chris,

Minerva's archetype should be pushed to public Maven repository, either Eclipse or Maven Central, it doesn't matter. This will make it more visible to outside world and consumed without building from the source.

**Comment by caniszczyk** [comment]
It's on my list to refactor the code base to 'org.eclipse.dash.minerva' namespace and have it contributed to the dash eclipse project and be available at maven.eclipse.org

**Comment by manandbytes** [comment]
The only thing that blocks deployment is a namespace, am I right? Any ETA if this is the case?

**Comment by caniszczyk** [comment]
The new namespace and some testing. On top of that, I'm waiting for my commit rights to be restored at eclipse.org since I moved to a new company :)
